import { useMemo, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import PageHeader from '../../components/PageHeader';
import type { AppLanguage } from '../../layout/AppLayout';

type WizardStep =
  | 'caseInfo'
  | 'reporter'
  | 'workflow'
  | 'indicators'
  | 'fraudDetails'
  | 'attachments'
  | 'review';

type PageCopy = {
  title: string;
  subtitle: string;
  saveDraft: string;
  submitCase: string;
  next: string;
  back: string;

  stepCaseInfo: string;
  stepReporter: string;
  stepWorkflow: string;
  stepIndicators: string;
  stepFraudDetails: string;
  stepAttachments: string;
  stepReview: string;

  autoGeneratedCaseId: string;
  claimId: string;
  caseSource: string;
  caseType: string;
  insuranceType: string;
  suspectedAmount: string;
  caseEntryDate: string;
  description: string;

  reporterName: string;
  email: string;
  mobileNumber: string;
  nationalId: string;

  assignedUser: string;
  caseStatus: string;
  assignmentDate: string;
  assignedBy: string;
  reassignmentReason: string;
  fraudUnitNotes: string;

  fraudIndicatorType: string;
  indicatorDescription: string;
  occurrenceCount: string;
  fraudOfficerDecision: string;

  claimType: string;
  fraudConfirmedDate: string;
  fraudDetectionMethod: string;
  fraudAmount: string;
  actionTaken: string;
  referredEntity: string;

  attachments: string;
  uploadHint: string;
  dragDropHint: string;
  noFiles: string;
  remove: string;

  reviewTitle: string;

  unassigned: string;
  statusOptions: string[];
  indicatorTypeOptions: string[];
  decisionOptions: string[];
  caseTypeOptions: string[];
  insuranceTypeOptions: string[];
  caseSourceOptions: string[];
  assignedByOptions: string[];
};

const pageCopy: Record<AppLanguage, PageCopy> = {
  en: {
    title: 'New Case',
    subtitle: 'Create a new fraud case step by step.',
    saveDraft: 'Save Draft',
    submitCase: 'Submit Case',
    next: 'Next',
    back: 'Back',

    stepCaseInfo: 'Case Information',
    stepReporter: 'Reporter Information',
    stepWorkflow: 'Workflow',
    stepIndicators: 'Fraud Indicators',
    stepFraudDetails: 'Confirmed Fraud Details',
    stepAttachments: 'Attachments',
    stepReview: 'Review',

    autoGeneratedCaseId: 'Auto-generated Case Id',
    claimId: 'Claim Id',
    caseSource: 'Case Source',
    caseType: 'Case Type',
    insuranceType: 'Insurance Type',
    suspectedAmount: 'Suspected Amount',
    caseEntryDate: 'Case Entry Date',
    description: 'Description',

    reporterName: 'Reporter Name',
    email: 'Email',
    mobileNumber: 'Mobile Number',
    nationalId: 'ID / Iqama Number',

    assignedUser: 'Assigned User',
    caseStatus: 'Case Status',
    assignmentDate: 'Assignment Date',
    assignedBy: 'Assigned By',
    reassignmentReason: 'Reassignment Reason',
    fraudUnitNotes: 'Fraud Unit Notes',

    fraudIndicatorType: 'Fraud Indicator Type',
    indicatorDescription: 'Indicator Description',
    occurrenceCount: 'Occurrence Count',
    fraudOfficerDecision: 'Fraud Officer Decision',

    claimType: 'Claim Type',
    fraudConfirmedDate: 'Fraud Confirmed Date',
    fraudDetectionMethod: 'Fraud Detection Method',
    fraudAmount: 'Fraud Amount',
    actionTaken: 'Action Taken',
    referredEntity: 'Referred Entity',

    attachments: 'Attachments',
    uploadHint: 'Upload files',
    dragDropHint: 'Drag and drop files here, or click to browse',
    noFiles: 'No files uploaded yet.',
    remove: 'Remove',

    reviewTitle: 'Review Entered Information',

    unassigned: 'Unassigned',
    statusOptions: ['New', 'Under Review', 'Under Investigation', 'Pending Information', 'Fraud Confirmed', 'Rejected', 'Closed'],
    indicatorTypeOptions: ['Duplicate Claims', 'Billing Pattern Anomaly', 'Policy Mismatch', 'Incomplete Evidence', 'High Value Repetition', 'Other'],
    decisionOptions: ['Proceed with investigation', 'Pending additional information', 'Fraud confirmed', 'Rejected', 'Close case'],
    caseTypeOptions: ['Fraud Suspected', 'Fraud Confirmed', 'Violation', 'Document Mismatch', 'Identity Concern'],
    insuranceTypeOptions: ['Motor', 'Medical', 'Property', 'Travel'],
    caseSourceOptions: ['Whistleblowing', 'Internal', 'Website', 'Call Center', 'Provider Audit', 'Customer Care'],
    assignedByOptions: ['System', 'Supervisor', 'Fraud Manager'],
  },
  ar: {
    title: 'بلاغ جديد',
    subtitle: 'إنشاء بلاغ احتيال جديد خطوة بخطوة.',
    saveDraft: 'حفظ كمسودة',
    submitCase: 'إرسال البلاغ',
    next: 'التالي',
    back: 'السابق',

    stepCaseInfo: 'معلومات البلاغ',
    stepReporter: 'بيانات المُبلّغ',
    stepWorkflow: 'سير العمل',
    stepIndicators: 'مؤشرات الاحتيال',
    stepFraudDetails: 'تفاصيل الاحتيال المؤكد',
    stepAttachments: 'المرفقات',
    stepReview: 'المراجعة',

    autoGeneratedCaseId: 'رقم البلاغ المُنشأ تلقائيًا',
    claimId: 'رقم المطالبة',
    caseSource: 'طريقة استقبال البلاغ',
    caseType: 'نوع البلاغ',
    insuranceType: 'نوع التأمين',
    suspectedAmount: 'المبلغ محل الاشتباه',
    caseEntryDate: 'تاريخ إدخال البلاغ',
    description: 'الوصف',

    reporterName: 'اسم المُبلّغ',
    email: 'البريد الإلكتروني',
    mobileNumber: 'رقم الجوال',
    nationalId: 'رقم الهوية / الإقامة',

    assignedUser: 'المستخدم المسؤول',
    caseStatus: 'حالة البلاغ',
    assignmentDate: 'تاريخ التعيين',
    assignedBy: 'تم التعيين بواسطة',
    reassignmentReason: 'سبب إعادة التعيين',
    fraudUnitNotes: 'ملاحظات وحدة مكافحة الاحتيال',

    fraudIndicatorType: 'نوع مؤشر الاحتيال',
    indicatorDescription: 'وصف المؤشر',
    occurrenceCount: 'عدد مرات التكرار',
    fraudOfficerDecision: 'قرار موظف وحدة مكافحة الاحتيال',

    claimType: 'نوع المطالبة',
    fraudConfirmedDate: 'تاريخ ثبوت الاحتيال',
    fraudDetectionMethod: 'آلية اكتشاف الاحتيال',
    fraudAmount: 'المبلغ المرتبط بالاحتيال',
    actionTaken: 'الإجراء المتخذ',
    referredEntity: 'الجهة المحالة لها',

    attachments: 'المرفقات',
    uploadHint: 'رفع ملفات',
    dragDropHint: 'اسحب وأفلت الملفات هنا أو اضغط للاختيار',
    noFiles: 'لا توجد ملفات مرفوعة حتى الآن.',
    remove: 'إزالة',

    reviewTitle: 'مراجعة المعلومات المدخلة',

    unassigned: 'غير معيّن',
    statusOptions: ['جديد', 'قيد المراجعة', 'قيد التحقيق', 'بانتظار معلومات', 'تم تأكيد الاحتيال', 'مرفوض', 'مغلق'],
    indicatorTypeOptions: ['مطالبات مكررة', 'شذوذ في نمط الفوترة', 'عدم تطابق الوثيقة', 'أدلة غير مكتملة', 'تكرار مبالغ عالية', 'أخرى'],
    decisionOptions: ['المتابعة والتحقيق', 'بانتظار معلومات إضافية', 'تم تأكيد الاحتيال', 'مرفوض', 'إغلاق البلاغ'],
    caseTypeOptions: ['اشتباه احتيال', 'تم تأكيد الاحتيال', 'مخالفة', 'عدم تطابق المستندات', 'اشتباه في الهوية'],
    insuranceTypeOptions: ['مركبات', 'طبي', 'ممتلكات', 'سفر'],
    caseSourceOptions: ['الإبلاغ الداخلي', 'داخلي', 'الموقع الإلكتروني', 'مركز الاتصال', 'تدقيق مقدم الخدمة', 'خدمة العملاء'],
    assignedByOptions: ['النظام', 'المشرف', 'مدير مكافحة الاحتيال'],
  },
};

const stepOrder: WizardStep[] = [
  'caseInfo',
  'reporter',
  'workflow',
  'indicators',
  'fraudDetails',
  'attachments',
  'review',
];

const generateCaseId = () => {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  const random = Math.floor(100 + Math.random() * 900);
  return `FC-${yyyy}${mm}${dd}-${random}`;
};

export default function NewCaseWizardPage() {
  const { language } = useOutletContext<{ language: AppLanguage }>();
  const t = useMemo(() => pageCopy[language], [language]);
  const isArabic = language === 'ar';

  const [currentStep, setCurrentStep] = useState<WizardStep>('caseInfo');
  const [caseId] = useState(generateCaseId());
  const [files, setFiles] = useState<File[]>([]);

  const [form, setForm] = useState({
    claimId: '',
    caseSource: '',
    caseType: '',
    insuranceType: '',
    suspectedAmount: '',
    caseEntryDate: '',
    description: '',

    reporterName: '',
    email: '',
    mobileNumber: '',
    nationalId: '',

    assignedUser: '',
    caseStatus: '',
    assignmentDate: '',
    assignedBy: '',
    reassignmentReason: '',
    fraudUnitNotes: '',

    fraudIndicatorType: '',
    indicatorDescription: '',
    occurrenceCount: '',
    fraudOfficerDecision: '',

    claimType: '',
    fraudConfirmedDate: '',
    fraudDetectionMethod: '',
    fraudAmount: '',
    actionTaken: '',
    referredEntity: '',
  });

  const currentStepIndex = stepOrder.indexOf(currentStep);

  const stepLabels: Record<WizardStep, string> = {
    caseInfo: t.stepCaseInfo,
    reporter: t.stepReporter,
    workflow: t.stepWorkflow,
    indicators: t.stepIndicators,
    fraudDetails: t.stepFraudDetails,
    attachments: t.stepAttachments,
    review: t.stepReview,
  };

  const updateField = (field: keyof typeof form, value: string) => {
    setForm((current) => ({ ...current, [field]: value }));
  };

  const goNext = () => {
    if (currentStepIndex < stepOrder.length - 1) {
      setCurrentStep(stepOrder[currentStepIndex + 1]);
    }
  };

  const goBack = () => {
    if (currentStepIndex > 0) {
      setCurrentStep(stepOrder[currentStepIndex - 1]);
    }
  };

  const handleFiles = (incomingFiles: FileList | null) => {
    if (!incomingFiles) return;
    setFiles((current) => [...current, ...Array.from(incomingFiles)]);
  };

  const removeFile = (indexToRemove: number) => {
    setFiles((current) => current.filter((_, index) => index !== indexToRemove));
  };

  return (
    <div dir={isArabic ? 'rtl' : 'ltr'}>
      <PageHeader
        title={t.title}
        subtitle={t.subtitle}
        action={
          <div className="actions-inline" style={{ gap: 12 }}>
            <button className="btn">{t.saveDraft}</button>
            <button className="btn primary">{t.submitCase}</button>
          </div>
        }
      />

      <div className="card" style={{ marginBottom: 20 }}>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: `repeat(${stepOrder.length}, minmax(0, 1fr))`,
            gap: 12,
            alignItems: 'start',
          }}
        >
          {stepOrder.map((step, index) => {
            const isActive = currentStep === step;
            const isCompleted = index < currentStepIndex;
            const stepNumber = index + 1;

            return (
              <button
                key={step}
                type="button"
                onClick={() => setCurrentStep(step)}
                style={{
                  border: 'none',
                  background: 'transparent',
                  padding: 0,
                  textAlign: isArabic ? 'right' : 'left',
                  cursor: 'pointer',
                }}
              >
                <div
                  style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 10,
                  }}
                >
                  <div
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 10,
                      flexDirection: isArabic ? 'row-reverse' : 'row',
                    }}
                  >
                    <div
                      style={{
                        width: 34,
                        height: 34,
                        minWidth: 34,
                        borderRadius: '999px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        fontWeight: 700,
                        fontSize: 14,
                        color: isActive || isCompleted ? '#fff' : '#0f172a',
                        background:
                          isActive || isCompleted
                            ? 'rgba(13, 108, 104, 0.95)'
                            : 'rgba(15, 23, 42, 0.08)',
                        border: isActive
                          ? '2px solid rgba(13, 108, 104, 1)'
                          : '2px solid transparent',
                      }}
                    >
                      {isCompleted ? '✓' : stepNumber}
                    </div>

                    <div style={{ minWidth: 0 }}>
                      <div
                        style={{
                          fontSize: 12,
                          color: 'rgba(15, 23, 42, 0.55)',
                          marginBottom: 2,
                        }}
                      >
                        {language === 'ar' ? `الخطوة ${stepNumber}` : `Step ${stepNumber}`}
                      </div>
                      <div
                        style={{
                          fontWeight: isActive ? 700 : 600,
                          color: isActive ? 'rgba(13, 108, 104, 1)' : 'inherit',
                          lineHeight: 1.25,
                        }}
                      >
                        {stepLabels[step]}
                      </div>
                    </div>
                  </div>

                  <div
                    style={{
                      height: 6,
                      borderRadius: 999,
                      background: 'rgba(15, 23, 42, 0.08)',
                      overflow: 'hidden',
                    }}
                  >
                    <div
                      style={{
                        height: '100%',
                        width: isCompleted ? '100%' : isActive ? '60%' : '0%',
                        background: 'rgba(13, 108, 104, 0.95)',
                        borderRadius: 999,
                        transition: 'width 0.25s ease',
                      }}
                    />
                  </div>
                </div>
              </button>
            );
          })}
        </div>
      </div>

      <div className="card">
        {currentStep === 'caseInfo' ? (
          <div className="form-grid">
            <label>
              <span>{t.autoGeneratedCaseId}</span>
              <input value={caseId} disabled />
            </label>
            <label>
              <span>{t.claimId}</span>
              <input value={form.claimId} onChange={(e) => updateField('claimId', e.target.value)} />
            </label>
            <label>
              <span>{t.caseSource}</span>
              <select value={form.caseSource} onChange={(e) => updateField('caseSource', e.target.value)}>
                <option value=""></option>
                {t.caseSourceOptions.map((option) => (
                  <option key={option}>{option}</option>
                ))}
              </select>
            </label>
            <label>
              <span>{t.caseType}</span>
              <select value={form.caseType} onChange={(e) => updateField('caseType', e.target.value)}>
                <option value=""></option>
                {t.caseTypeOptions.map((option) => (
                  <option key={option}>{option}</option>
                ))}
              </select>
            </label>
            <label>
              <span>{t.insuranceType}</span>
              <select value={form.insuranceType} onChange={(e) => updateField('insuranceType', e.target.value)}>
                <option value=""></option>
                {t.insuranceTypeOptions.map((option) => (
                  <option key={option}>{option}</option>
                ))}
              </select>
            </label>
            <label>
              <span>{t.suspectedAmount}</span>
              <input value={form.suspectedAmount} onChange={(e) => updateField('suspectedAmount', e.target.value)} />
            </label>
            <label>
              <span>{t.caseEntryDate}</span>
              <input type="date" value={form.caseEntryDate} onChange={(e) => updateField('caseEntryDate', e.target.value)} />
            </label>
            <label style={{ gridColumn: '1 / -1' }}>
              <span>{t.description}</span>
              <textarea rows={5} value={form.description} onChange={(e) => updateField('description', e.target.value)} />
            </label>
          </div>
        ) : null}

        {currentStep === 'reporter' ? (
          <div className="form-grid">
            <label>
              <span>{t.reporterName}</span>
              <input value={form.reporterName} onChange={(e) => updateField('reporterName', e.target.value)} />
            </label>
            <label>
              <span>{t.email}</span>
              <input value={form.email} onChange={(e) => updateField('email', e.target.value)} />
            </label>
            <label>
              <span>{t.mobileNumber}</span>
              <input value={form.mobileNumber} onChange={(e) => updateField('mobileNumber', e.target.value)} />
            </label>
            <label>
              <span>{t.nationalId}</span>
              <input value={form.nationalId} onChange={(e) => updateField('nationalId', e.target.value)} />
            </label>
          </div>
        ) : null}

        {currentStep === 'workflow' ? (
          <div className="form-grid">
            <label>
              <span>{t.assignedUser}</span>
              <input value={form.assignedUser} onChange={(e) => updateField('assignedUser', e.target.value)} placeholder={t.unassigned} />
            </label>
            <label>
              <span>{t.caseStatus}</span>
              <select value={form.caseStatus} onChange={(e) => updateField('caseStatus', e.target.value)}>
                <option value=""></option>
                {t.statusOptions.map((option) => (
                  <option key={option}>{option}</option>
                ))}
              </select>
            </label>
            <label>
              <span>{t.assignmentDate}</span>
              <input type="date" value={form.assignmentDate} onChange={(e) => updateField('assignmentDate', e.target.value)} />
            </label>
            <label>
              <span>{t.assignedBy}</span>
              <select value={form.assignedBy} onChange={(e) => updateField('assignedBy', e.target.value)}>
                <option value=""></option>
                {t.assignedByOptions.map((option) => (
                  <option key={option}>{option}</option>
                ))}
              </select>
            </label>
            <label>
              <span>{t.reassignmentReason}</span>
              <input value={form.reassignmentReason} onChange={(e) => updateField('reassignmentReason', e.target.value)} />
            </label>
            <label style={{ gridColumn: '1 / -1' }}>
              <span>{t.fraudUnitNotes}</span>
              <textarea rows={5} value={form.fraudUnitNotes} onChange={(e) => updateField('fraudUnitNotes', e.target.value)} />
            </label>
          </div>
        ) : null}

        {currentStep === 'indicators' ? (
          <div className="form-grid">
            <label>
              <span>{t.fraudIndicatorType}</span>
              <select value={form.fraudIndicatorType} onChange={(e) => updateField('fraudIndicatorType', e.target.value)}>
                <option value=""></option>
                {t.indicatorTypeOptions.map((option) => (
                  <option key={option}>{option}</option>
                ))}
              </select>
            </label>
            <label>
              <span>{t.occurrenceCount}</span>
              <input value={form.occurrenceCount} onChange={(e) => updateField('occurrenceCount', e.target.value)} />
            </label>
            <label style={{ gridColumn: '1 / -1' }}>
              <span>{t.indicatorDescription}</span>
              <textarea rows={5} value={form.indicatorDescription} onChange={(e) => updateField('indicatorDescription', e.target.value)} />
            </label>
            <label>
              <span>{t.fraudOfficerDecision}</span>
              <select value={form.fraudOfficerDecision} onChange={(e) => updateField('fraudOfficerDecision', e.target.value)}>
                <option value=""></option>
                {t.decisionOptions.map((option) => (
                  <option key={option}>{option}</option>
                ))}
              </select>
            </label>
          </div>
        ) : null}

        {currentStep === 'fraudDetails' ? (
          <div className="form-grid">
            <label>
              <span>{t.claimType}</span>
              <input value={form.claimType} onChange={(e) => updateField('claimType', e.target.value)} />
            </label>
            <label>
              <span>{t.fraudConfirmedDate}</span>
              <input type="date" value={form.fraudConfirmedDate} onChange={(e) => updateField('fraudConfirmedDate', e.target.value)} />
            </label>
            <label>
              <span>{t.fraudDetectionMethod}</span>
              <input value={form.fraudDetectionMethod} onChange={(e) => updateField('fraudDetectionMethod', e.target.value)} />
            </label>
            <label>
              <span>{t.fraudAmount}</span>
              <input value={form.fraudAmount} onChange={(e) => updateField('fraudAmount', e.target.value)} />
            </label>
            <label>
              <span>{t.actionTaken}</span>
              <input value={form.actionTaken} onChange={(e) => updateField('actionTaken', e.target.value)} />
            </label>
            <label>
              <span>{t.referredEntity}</span>
              <input value={form.referredEntity} onChange={(e) => updateField('referredEntity', e.target.value)} />
            </label>
          </div>
        ) : null}

        {currentStep === 'attachments' ? (
          <div className="form-grid single">
            <div>
              <span>{t.attachments}</span>
              <label
                style={{
                  display: 'block',
                  marginTop: 12,
                  border: '2px dashed rgba(15, 23, 42, 0.18)',
                  borderRadius: 16,
                  padding: 24,
                  textAlign: 'center',
                  cursor: 'pointer',
                }}
                onDragOver={(e) => e.preventDefault()}
                onDrop={(e) => {
                  e.preventDefault();
                  handleFiles(e.dataTransfer.files);
                }}
              >
                <input
                  type="file"
                  multiple
                  style={{ display: 'none' }}
                  onChange={(e) => handleFiles(e.target.files)}
                />
                <strong>{t.uploadHint}</strong>
                <div className="muted" style={{ marginTop: 8 }}>
                  {t.dragDropHint}
                </div>
              </label>

              <div className="activity-list top-gap">
                {files.length > 0 ? (
                  files.map((file, index) => (
                    <div className="activity-item" key={`${file.name}-${index}`}>
                      <div>
                        <strong>{file.name}</strong>
                        <span>{Math.round(file.size / 1024)} KB</span>
                      </div>
                      <button className="btn" type="button" onClick={() => removeFile(index)}>
                        {t.remove}
                      </button>
                    </div>
                  ))
                ) : (
                  <div className="activity-item">
                    <strong>{t.noFiles}</strong>
                  </div>
                )}
              </div>
            </div>
          </div>
        ) : null}

        {currentStep === 'review' ? (
          <div className="form-grid single">
            <h3>{t.reviewTitle}</h3>
            <div className="activity-list">
              <div className="activity-item"><strong>{t.autoGeneratedCaseId}</strong><span>{caseId}</span></div>
              <div className="activity-item"><strong>{t.claimId}</strong><span>{form.claimId || '-'}</span></div>
              <div className="activity-item"><strong>{t.caseSource}</strong><span>{form.caseSource || '-'}</span></div>
              <div className="activity-item"><strong>{t.caseType}</strong><span>{form.caseType || '-'}</span></div>
              <div className="activity-item"><strong>{t.insuranceType}</strong><span>{form.insuranceType || '-'}</span></div>
              <div className="activity-item"><strong>{t.suspectedAmount}</strong><span>{form.suspectedAmount || '-'}</span></div>
              <div className="activity-item"><strong>{t.reporterName}</strong><span>{form.reporterName || '-'}</span></div>
              <div className="activity-item"><strong>{t.email}</strong><span>{form.email || '-'}</span></div>
              <div className="activity-item"><strong>{t.mobileNumber}</strong><span>{form.mobileNumber || '-'}</span></div>
              <div className="activity-item"><strong>{t.attachments}</strong><span>{files.length}</span></div>
            </div>
          </div>
        ) : null}

        <div className="actions-inline" style={{ gap: 12, marginTop: 24 }}>
          {currentStepIndex > 0 ? (
            <button className="btn" type="button" onClick={goBack}>
              {t.back}
            </button>
          ) : null}

          {currentStepIndex < stepOrder.length - 1 ? (
            <button className="btn primary" type="button" onClick={goNext}>
              {t.next}
            </button>
          ) : (
            <button className="btn primary" type="button">
              {t.submitCase}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
